### ISSUE TITLE
MailChimp 'continue to our website' redirect causes error.

### ISSUE THREAD

**Issue by JoeKarow** [Virtual-Coffee/virtualcoffee.io#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When signing up for the news letter, clicking on the "continue to our website" button on the MailChimp confirmation page returns the following error:

Application Error
FetchError: request to https://virtualcoffee.io/.netlify/builders/data-sponsors failed, reason: connect ECONNREFUSED 34.204.131.44:443
    at ClientRequest.<anonymous> (/var/task/node_modules/@remix-run/node/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

### Steps To Reproduce

1. Sign up for newsletter
2. Click "continue to our website"
3. ???
4. Error!

### What browsers are you seeing the problem on?

Chrome

### Environment

```markdown
- OS: macOS Monterey 12.3.1
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by danieltott** [comment]
@tkshill do you know what the "continue to our site" url is?

**Comment by danieltott** [comment]
It looks like the link is correct (its just the home page) - I've been unable to reproduce this error.

Seems like a weird netlify and/or remix hiccup...

**Comment by JoeKarow** [comment]
Maybe I was just in the wrong place at the wrong time.
