### ISSUE TITLE
Convert `MemberCards.jsx` to typescript

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

Continuing our typescript conversion - let's convert [`app/components/MemberCards.jsx` ](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/app/components/MemberCards.jsx) to typescript!

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by danieltott** [comment]
Hey @Croustys - thanks for the interest but this issue is reserved for Virtual Coffee members.

**Comment by JesseRWeigel** [comment]
yo

**Comment by JesseRWeigel** [comment]
I got all the ts errors fixed for MemberCards and all of the icons, but this is causing an error in `members.ts`. You can see my code here: https://github.com/JesseRWeigel/virtualcoffee.io/tree/refactor/660/memberCardToTSX . I am not sure how to handle this issue. This is the error log: 
```
Request from ::1: GET /.netlify/functions/server
There was an error running the data loader for route routes/__frontend/members/index
TypeError: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:564:9)
    at parse (<anonymous>)
    at new URL (node:internal/url:640:5)
    at new Request (C:\Users\jesse\Projects\virtualcoffee.io\node_modules\@remix-run\web-fetch\src\request.js:76:16)
    at C:\Users\jesse\Projects\virtualcoffee.io\node_modules\@remix-run\web-fetch\src\fetch.js:42:19
    at new Promise (<anonymous>)
    at AsyncFunction.fetch (C:\Users\jesse\Projects\virtualcoffee.io\node_modules\@remix-run\web-fetch\src\fetch.js:40:9)
    at fetch (C:\Users\jesse\Projects\virtualcoffee.io\node_modules\@remix-run\node\dist\fetch.js:50:19)
    at getMembers (C:\Users\jesse\Projects\virtualcoffee.io\app\data\members.ts:10:42)
Response with status 500 in 993 ms.
```

**Comment by danieltott** [comment]
@JesseRWeigel did you create the .env file? That might cause this issue
